# Generated by Django 5.2.5 on 2025-09-02 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('entity', models.CharField(max_length=200, verbose_name='Entity/Organization')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('number_of_users', models.IntegerField(verbose_name='Number of Users')),
                ('laptop_bureautique', models.IntegerField(default=0, verbose_name='Office Laptops')),
                ('laptop_technique', models.IntegerField(default=0, verbose_name='Technical Laptops')),
                ('desktop_bureautique', models.IntegerField(default=0, verbose_name='Office Desktops')),
                ('desktop_technique', models.IntegerField(default=0, verbose_name='Technical Desktops')),
                ('printers', models.IntegerField(default=0, verbose_name='Printers')),
                ('workstations', models.IntegerField(default=0, verbose_name='Workstations')),
                ('video_conference', models.IntegerField(default=0, verbose_name='Video Conference Systems')),
                ('access_points', models.IntegerField(default=0, verbose_name='Access Points')),
                ('file_server_needed', models.BooleanField(default=False, verbose_name='File Server Needed')),
                ('internet_speed', models.CharField(blank=True, max_length=50, verbose_name='Internet Speed')),
                ('local_applications', models.BooleanField(default=False, verbose_name='Local Applications')),
                ('local_apps_description', models.TextField(blank=True, verbose_name='Local Applications Description')),
                ('addresses', models.TextField(verbose_name='Site Addresses')),
                ('gps_coordinates', models.TextField(blank=True, verbose_name='GPS Coordinates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cost_france', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Cost (France)')),
                ('total_cost_morocco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Cost (Morocco)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
