# Generated by Django 5.2.5 on 2025-09-08 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_networkequipment_serverequipment_service_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="entity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENTITY_A", "Entité A"),
                    ("ENTITY_B", "Entité B"),
                    ("OTHER", "Autre"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="file_server",
            field=models.BooleanField(
                default=False, help_text="Serveur de fichiers présent ?"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="gps_coordinates",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Coordonnées GPS (ex: 24.793387, 46.654397)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="internet_line_speed",
            field=models.CharField(
                blank=True, default="", help_text="Ex: 100Mbps", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="internet_line_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FO", "FO"),
                    ("VSAT", "VSAT"),
                    ("STARLINK", "STARLINK"),
                    ("OTHER", "Autre"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="local_apps",
            field=models.BooleanField(
                default=False, help_text="Y a-t-il des applications locales ?"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="local_apps_list",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Liste des applications locales (ex: SAGE, GMAO)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="num_aps",
            field=models.PositiveIntegerField(
                default=0, help_text="Nombre de points d'accès (AP)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="num_desktop_office",
            field=models.PositiveIntegerField(
                default=0, help_text="Nombre de desktop bureautique"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="num_desktop_tech",
            field=models.PositiveIntegerField(
                default=0, help_text="Nombre de desktop technique"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="num_laptop_office",
            field=models.PositiveIntegerField(
                default=0, help_text="Nombre de laptop bureautique"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="num_laptop_tech",
            field=models.PositiveIntegerField(
                default=0, help_text="Nombre de laptop technique"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="num_printers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="num_traceau",
            field=models.PositiveIntegerField(default=0, help_text="Nombre de traceau"),
        ),
        migrations.AddField(
            model_name="project",
            name="num_videoconference",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_users",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="pc_type",
            field=models.CharField(
                choices=[
                    ("LAPTOP_ONLY", "Laptop uniquement"),
                    ("DESKTOP_ONLY", "Desktop uniquement"),
                    ("BOTH", "Les deux"),
                ],
                default="BOTH",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="site_addresses",
            field=models.TextField(
                blank=True, default="", help_text="Adresses de chaque site/atelier"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="projectnetworkitem",
            name="purchase_location",
            field=models.CharField(
                choices=[("FR", "France"), ("LOCAL", "Local")],
                default="FR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectserveritem",
            name="purchase_location",
            field=models.CharField(
                choices=[("FR", "France"), ("LOCAL", "Local")],
                default="FR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectserviceitem",
            name="purchase_location",
            field=models.CharField(
                choices=[("FR", "France"), ("LOCAL", "Local")],
                default="FR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectsoftwareitem",
            name="purchase_location",
            field=models.CharField(
                choices=[("FR", "France"), ("LOCAL", "Local")],
                default="FR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectuserdeviceitem",
            name="purchase_location",
            field=models.CharField(
                choices=[("FR", "France"), ("LOCAL", "Local")],
                default="FR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="networkequipment",
            name="port_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Nombre de ports.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="networkequipment",
            name="speed",
            field=models.CharField(
                blank=True,
                help_text="Vitesse des ports (ex: 1Gbps).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="network_equipment",
            field=models.ManyToManyField(
                blank=True,
                through="projects.ProjectNetworkItem",
                to="projects.networkequipment",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="server_equipment",
            field=models.ManyToManyField(
                blank=True,
                through="projects.ProjectServerItem",
                to="projects.serverequipment",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="services",
            field=models.ManyToManyField(
                blank=True, through="projects.ProjectServiceItem", to="projects.service"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="software_licenses",
            field=models.ManyToManyField(
                blank=True,
                through="projects.ProjectSoftwareItem",
                to="projects.softwarelicense",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user_devices",
            field=models.ManyToManyField(
                blank=True,
                through="projects.ProjectUserDeviceItem",
                to="projects.userdevice",
            ),
        ),
        migrations.AlterField(
            model_name="projectnetworkitem",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="projectserveritem",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="projectserviceitem",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="projectsoftwareitem",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="projectuserdeviceitem",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="serverequipment",
            name="cpu",
            field=models.CharField(
                blank=True, help_text="CPU modèle.", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="serverequipment",
            name="rack_units",
            field=models.PositiveIntegerField(
                blank=True, help_text="Hauteur en U.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="serverequipment",
            name="ram_gb",
            field=models.PositiveIntegerField(
                blank=True, help_text="RAM en GB.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="bandwidth_mbps",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="sla_response_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="softwarelicense",
            name="user_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="screen_size",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="storage_gb",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="projectnetworkitem",
            unique_together={("project", "equipment")},
        ),
        migrations.AlterUniqueTogether(
            name="projectserveritem",
            unique_together={("project", "equipment")},
        ),
        migrations.AlterUniqueTogether(
            name="projectserviceitem",
            unique_together={("project", "equipment")},
        ),
        migrations.AlterUniqueTogether(
            name="projectsoftwareitem",
            unique_together={("project", "equipment")},
        ),
        migrations.AlterUniqueTogether(
            name="projectuserdeviceitem",
            unique_together={("project", "equipment")},
        ),
    ]
