# Generated by Django 5.2.5 on 2025-09-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_options_project_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfrastructureEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom spécifique de l'article.", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fixed_cost_eur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fixed_cost_mad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monthly_cost_eur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monthly_cost_mad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "infra_type",
                    models.CharField(
                        choices=[
                            ("RACK", "Rack"),
                            ("UPS", "Onduleur"),
                            ("CABLE", "Câble réseau"),
                            ("KVM", "KVM Console/Switch"),
                            ("ACCESSORY", "Accessoire"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Longueur (pour câbles)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "port_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Nombre de ports (pour KVM)", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectInfrastructureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("source", models.CharField(blank=True, default="", max_length=50)),
                (
                    "purchase_location",
                    models.CharField(
                        choices=[("FR", "France"), ("LOCAL", "Local")],
                        default="FR",
                        max_length=10,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.infrastructureequipment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "equipment")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="infrastructure_equipment",
            field=models.ManyToManyField(
                blank=True,
                through="projects.ProjectInfrastructureItem",
                to="projects.infrastructureequipment",
            ),
        ),
    ]
