# Generated by Django 5.2.5 on 2025-09-08 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_infrastructureequipment_projectinfrastructureitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisioEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom spécifique de l'article.", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fixed_cost_eur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fixed_cost_mad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monthly_cost_eur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monthly_cost_mad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "visio_type",
                    models.CharField(
                        choices=[
                            ("HARDWARE_CODEC", "Hardware codec (room system)"),
                            ("SOFTWARE", "Software (Teams/Zoom)"),
                            ("ROOM_SYSTEM", "Room system"),
                            ("SIP_H323", "SIP / H.323"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "supported_users",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre d'utilisateurs supportés (approx.)",
                        null=True,
                    ),
                ),
                (
                    "ports",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre de ports (si applicable)",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="visio_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HARDWARE_CODEC", "Hardware codec (room system)"),
                    ("SOFTWARE", "Software (Teams/Zoom)"),
                    ("ROOM_SYSTEM", "Room system"),
                    ("SIP_H323", "SIP / H.323"),
                    ("OTHER", "Autre"),
                ],
                help_text="Type de visioconférence (ex: room system, software, SIP/H.323)",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="infrastructureequipment",
            name="length_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Longueur (m) — pour câbles",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProjectVisioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("source", models.CharField(blank=True, default="", max_length=50)),
                (
                    "purchase_location",
                    models.CharField(
                        choices=[("FR", "France"), ("LOCAL", "Local")],
                        default="FR",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.visioequipment",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "equipment")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="visio_equipment",
            field=models.ManyToManyField(
                blank=True,
                through="projects.ProjectVisioItem",
                to="projects.visioequipment",
            ),
        ),
    ]
