# Generated by Django 5.2.5 on 2025-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_visioequipment_project_visio_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='entity',
            field=models.CharField(blank=True, choices=[('BOUYGUES_CONSTRUCTION', 'Bouygues Construction'), ('BOUYGUES_IMMOBILIER', 'Bouygues Immobilier'), ('COLAS', 'Colas'), ('TF1', 'TF1'), ('BOUYGUES_ENERGIES_SERVICES', 'Bouygues Energies & Services'), ('EQUANS', 'Equans'), ('BOUYGUES_TELECOM', 'Bouygues Telecom'), ('BOUYGUES_SA', 'Bouygues SA (Holding)'), ('OTHER', 'Autre')], max_length=50, null=True),
        ),
    ]
