# Generated by Django 5.2.5 on 2025-09-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_entity'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE projects_project MODIFY COLUMN status VARCHAR(20) DEFAULT 'draft'",
            reverse_sql="ALTER TABLE projects_project MODIFY COLUMN status VARCHAR(20)",
        ),
    ]
