# Generated by Django 5.2.5 on 2025-09-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_status'),
    ]

    operations = [
        # Fix description field defaults for all equipment tables
        migrations.RunSQL(
            "ALTER TABLE projects_networkequipment MODIFY COLUMN description TEXT DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_networkequipment MODIFY COLUMN description TEXT",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_serverequipment MODIFY COLUMN description TEXT DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_serverequipment MODIFY COLUMN description TEXT",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_userdevice MODIFY COLUMN description TEXT DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_userdevice MODIFY COLUMN description TEXT",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_softwarelicense MODIFY COLUMN description TEXT DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_softwarelicense MODIFY COLUMN description TEXT",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_service MODIFY COLUMN description TEXT DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_service MODIFY COLUMN description TEXT",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_visioequipment MODIFY COLUMN description TEXT DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_visioequipment MODIFY COLUMN description TEXT",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_infrastructureequipment MODIFY COLUMN description TEXT DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_infrastructureequipment MODIFY COLUMN description TEXT",
        ),
        # Fix supplier field defaults
        migrations.RunSQL(
            "ALTER TABLE projects_networkequipment MODIFY COLUMN supplier VARCHAR(255) DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_networkequipment MODIFY COLUMN supplier VARCHAR(255)",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_serverequipment MODIFY COLUMN supplier VARCHAR(255) DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_serverequipment MODIFY COLUMN supplier VARCHAR(255)",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_userdevice MODIFY COLUMN supplier VARCHAR(255) DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_userdevice MODIFY COLUMN supplier VARCHAR(255)",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_softwarelicense MODIFY COLUMN supplier VARCHAR(255) DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_softwarelicense MODIFY COLUMN supplier VARCHAR(255)",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_service MODIFY COLUMN supplier VARCHAR(255) DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_service MODIFY COLUMN supplier VARCHAR(255)",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_visioequipment MODIFY COLUMN supplier VARCHAR(255) DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_visioequipment MODIFY COLUMN supplier VARCHAR(255)",
        ),
        migrations.RunSQL(
            "ALTER TABLE projects_infrastructureequipment MODIFY COLUMN supplier VARCHAR(255) DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_infrastructureequipment MODIFY COLUMN supplier VARCHAR(255)",
        ),
    ]