# Generated by Django 5.2.5 on 2025-09-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20250915_1000'),
    ]

    operations = [
        # Fix description field in Project table if it exists
        migrations.RunSQL(
            "ALTER TABLE projects_project MODIFY COLUMN description TEXT DEFAULT NULL",
            reverse_sql="ALTER TABLE projects_project MODIFY COLUMN description TEXT",
        ),
    ]
