# Generated by Django 5.2.5 on 2025-09-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20250915_1000'),
    ]

    operations = [
        # SQLite doesn't support MODIFY COLUMN, so this migration is empty
        # The fields will be created with proper defaults in the model definitions
    ]
