# Generated by Django 5.2.5 on 2025-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20250915_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
    ]
