# Generated by Django 5.2.5 on 2025-09-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_priority_project_progress_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_cost_france',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost in EUR', max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='total_cost_morocco',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost in MAD', max_digits=12),
        ),
    ]
