# Generated by Django 5.2.5 on 2025-09-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_budget_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_switch_24',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de switch 24 ports'),
        ),
        migrations.AddField(
            model_name='project',
            name='num_switch_48',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de switch 48 ports'),
        ),
    ]