# Generated by Django 5.2.6 on 2025-09-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_add_missing_status_priority'),
    ]

    operations = [
        # Remove legacy equipment models and their related tables
        migrations.DeleteModel(
            name='ProjectVisioItem',
        ),
        migrations.DeleteModel(
            name='ProjectServiceItem',
        ),
        migrations.DeleteModel(
            name='ProjectSoftwareItem',
        ),
        migrations.DeleteModel(
            name='ProjectUserDeviceItem',
        ),
        migrations.DeleteModel(
            name='ProjectInfrastructureItem',
        ),
        migrations.DeleteModel(
            name='ProjectServerItem',
        ),
        migrations.DeleteModel(
            name='ProjectNetworkItem',
        ),
        migrations.DeleteModel(
            name='VisioEquipment',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SoftwareLicense',
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
        migrations.DeleteModel(
            name='InfrastructureEquipment',
        ),
        migrations.DeleteModel(
            name='ServerEquipment',
        ),
        migrations.DeleteModel(
            name='NetworkEquipment',
        ),
    ]
