# Generated by Django 5.2.6 on 2025-09-23 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Material Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_france', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (France - €)')),
                ('price_morocco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Morocco - MAD)')),
                ('is_auto_calculated', models.BooleanField(default=False, verbose_name='Auto Calculated')),
                ('is_service', models.BooleanField(default=False, verbose_name='Is Service')),
                ('unit', models.CharField(default='unit', max_length=20, verbose_name='Unit')),
                ('calculation_type', models.CharField(choices=[('PER_USER', 'Per User'), ('PER_SERVER', 'Per Server'), ('PER_DEVICE', 'Per Computer/Device'), ('PER_SWITCH', 'Per Switch'), ('PER_PROJECT', 'Per Project'), ('FIXED', 'Fixed Amount'), ('CONDITIONAL', 'Conditional')], default='FIXED', max_length=20, verbose_name='Calculation Type')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='How many units per user/server/project', max_digits=5, verbose_name='Multiplier')),
                ('min_quantity', models.IntegerField(default=0, help_text='Minimum quantity to add', verbose_name='Min Quantity')),
                ('max_quantity', models.IntegerField(default=999999, help_text='Maximum quantity to add', verbose_name='Max Quantity')),
                ('conditions', models.JSONField(default=dict, help_text="Calculation conditions (e.g., {'min_users': 50})", verbose_name='Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.category')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price_france', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price_france', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price_morocco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price_morocco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='materials.material')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
