# Generated by Django 5.2.5 on 2025-09-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_add_smart_calculation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='calculation_type',
            field=models.CharField(choices=[('PER_USER', 'Per User'), ('PER_SERVER', 'Per Server'), ('PER_DEVICE', 'Per Computer/Device'), ('PER_PROJECT', 'Per Project'), ('FIXED', 'Fixed Amount'), ('CONDITIONAL', 'Conditional')], default='FIXED', max_length=20, verbose_name='Calculation Type'),
        ),
    ]
