# Generated by Django 5.2.6 on 2025-09-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_add_per_device_calculation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='calculation_type',
            field=models.CharField(choices=[('PER_USER', 'Per User (Number of Users)'), ('PER_SERVER', 'Per Server'), ('PER_PC', 'Per PC (Number of PCs)'), ('PER_DEVICE', 'Per Device'), ('PER_WORKSTATION', 'Per Workstation'), ('PER_OFFICE', 'Per Office Location'), ('PER_SWITCH', 'Per Switch'), ('PER_PROJECT', 'Per Project'), ('FIXED', 'Fixed Amount'), ('CONDITIONAL', 'Conditional (Based on Requirements)')], default='FIXED', max_length=20, verbose_name='Calculation Type'),
        ),
    ]
