# Generated by Django 5.2.5 on 2025-09-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('formula', models.TextField(help_text='Python expression for calculation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('is_auto_calculated', models.BooleanField(default=False, verbose_name='Auto Calculated')),
                ('unit_cost_france', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost (France)')),
                ('unit_cost_morocco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost (Morocco)')),
                ('total_cost_france', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Cost (France)')),
                ('total_cost_morocco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Cost (Morocco)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.project')),
            ],
            options={
                'ordering': ['material__category__name', 'material__name'],
                'unique_together': {('project', 'material')},
            },
        ),
    ]
